//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoTieuChi
    {
        public BoTieuChi()
        {
            this.ChiTietBoTieuChis = new HashSet<ChiTietBoTieuChi>();
        }
    
        public int IDBoTieuChi { get; set; }
        public int HocKy { get; set; }
        public string NamHoc { get; set; }
        public Nullable<int> MaNhom { get; set; }
        public int DiemNhom { get; set; }
        public Nullable<int> IDNguoiTao { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual NhomTieuChi NhomTieuChi { get; set; }
        public virtual ICollection<ChiTietBoTieuChi> ChiTietBoTieuChis { get; set; }
    }
}
