//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBoTieuChi
    {
        public ChiTietBoTieuChi()
        {
            this.DiemTuyChons = new HashSet<DiemTuyChon>();
        }
    
        public int IDChiTietBo { get; set; }
        public Nullable<int> IDBoTieuChi { get; set; }
        public Nullable<int> MaTieuChi { get; set; }
        public int DiemTieuChi { get; set; }
        public Nullable<int> DiemMin { get; set; }
    
        public virtual BoTieuChi BoTieuChi { get; set; }
        public virtual TieuChi TieuChi { get; set; }
        public virtual ICollection<DiemTuyChon> DiemTuyChons { get; set; }
    }
}
