//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemTuyChon
    {
        public int IDTuyChon { get; set; }
        public Nullable<int> IDChiTietBo { get; set; }
        public Nullable<int> MaTuyChon { get; set; }
        public int DiemTuyChon1 { get; set; }
    
        public virtual ChiTietBoTieuChi ChiTietBoTieuChi { get; set; }
        public virtual TuyChonTieuChi TuyChonTieuChi { get; set; }
    }
}
