//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomTieuChi_BoTieuChi
    {
        public NhomTieuChi_BoTieuChi()
        {
            this.ChiTietBoTieuChis = new HashSet<ChiTietBoTieuChi>();
        }
    
        public int IDBoTieuChi { get; set; }
        public int MaNhom { get; set; }
        public Nullable<int> DiemNhom { get; set; }
    
        public virtual BoTieuChi BoTieuChi { get; set; }
        public virtual ICollection<ChiTietBoTieuChi> ChiTietBoTieuChis { get; set; }
        public virtual NhomTieuChi NhomTieuChi { get; set; }
    }
}
