//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhomTieuChi
    {
        public NhomTieuChi()
        {
            this.TieuChis = new HashSet<TieuChi>();
        }
    
        public int MaNhom { get; set; }
        public string TenNhom { get; set; }
    
        public virtual ICollection<TieuChi> TieuChis { get; set; }
    }
}
