//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyTieuChuanTieuChiEntities : DbContext
    {
        public QuanLyTieuChuanTieuChiEntities()
            : base("name=QuanLyTieuChuanTieuChiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoTieuChi> BoTieuChis { get; set; }
        public virtual DbSet<ChiTietBoTieuChi> ChiTietBoTieuChis { get; set; }
        public virtual DbSet<DiemTuyChon> DiemTuyChons { get; set; }
        public virtual DbSet<NhomTieuChi> NhomTieuChis { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TieuChi> TieuChis { get; set; }
        public virtual DbSet<TuyChonTieuChi> TuyChonTieuChis { get; set; }
    }
}
