//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class TieuChi
    {
        public TieuChi()
        {
            this.ChiTietBoTieuChis = new HashSet<ChiTietBoTieuChi>();
            this.TuyChonTieuChis = new HashSet<TuyChonTieuChi>();
        }
    
        public int MaTieuChi { get; set; }
        public Nullable<int> MaNhom { get; set; }
        public string NoiDung { get; set; }
        public int KieuHienThiTuyChon { get; set; }
        public string MoTaTieuChi { get; set; }
        public int IDNguoiTao { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual ICollection<ChiTietBoTieuChi> ChiTietBoTieuChis { get; set; }
        public virtual NhomTieuChi NhomTieuChi { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual ICollection<TuyChonTieuChi> TuyChonTieuChis { get; set; }
    }
}
