Insert into TaiKhoan values ('admin','123456','admin',0)
Insert into TaiKhoan values ('staff','123456','XH',1)

insert into NhomTieuChi values (N'Đánh giá ý thức tham gia học tập')
insert into NhomTieuChi values (N'Đánh giá về ý thức chấp hành nội quy, quy chế, quy định trong nhà trường')
insert into NhomTieuChi values (N'Đánh giá về ý thức và kết quả tham gia các hoạt động chính trị - xã hội, văn hóa, văn nghệ, thể thao, phòng chống các tệ nạn xã hội')
insert into NhomTieuChi values (N'Đánh giá về ý thức công dân trong quan hệ cộng đồng')
insert into NhomTieuChi values (N'Đánh giá về ý thức và kết quả tham gia công tác cán bộ lớp, các đoàn thể, tổ chức trong cơ sở giáo dục đại học hoặc người học đạt được thành tích đặc biệt trong học tập, rèn luyện')

insert into TieuChi values (1,N'Có đi học chuyên cần, đúng giờ, nghiêm túc trong giờ học',2,null,1,'1/1/2018')
insert into TieuChi values (1,N'Có đăng ký, thực hiện, báo cáo đề tài nghiên cứu khoa học đúng tiến độ hoặc có đăng ký, tham dự các cuộc thi học thuật cấp Khoa trở lên',2,null,1,'1/1/2018')
insert into TieuChi values (1,N'Có ý thức tham gia các câu lạc bộ, câu lạc bộ học thuật, các hoạt động học thuật, hoạt động ngoại khóa',2,null,1,'1/1/2018')
insert into TieuChi values (1,N'Bị xử lý kỷ luật trong các kỳ thi kết thúc học phần',0,N'khiển trách: -2 điểm, cảnh cáo: -4 điểm, đình chỉ thi: -6 điểm',1,'1/1/2018')
insert into TieuChi values (1,N'Được tập thể lớp công nhận có tinh thần vượt khó, phấn đấu vươn lên trong học tập',2,null,1,'1/1/2018')
insert into TieuChi values (1,N'Kết quả học tập',0,N'Yếu kém: 0 điểm; Trung bình: 4 điểm; Khá: 6 điểm; Giỏi: 8 điểm; Xuất sắc: 10 điểm',1,'1/1/2018')
insert into TieuChi values (2,N'Có ý thức chấp hành các văn bản chỉ đạo của ngành, của trường được thực hiện trong nhà trường',0,N'Vi phạm 01 lần bị trừ 02 điểm, từ lần vi phạm thứ hai trở đi bị trừ hết số điểm còn lại của tiêu chí',1,'1/1/2018')
insert into TieuChi values (2,N'Có ý thức tham gia đầy đủ, đạt yêu cầu các cuộc vận động, sinh hoạt chính trị theo chủ trương, của cấp trên và nhà trường',0,N'Không tham gia 01 lần hoặc vi phạm quy định của các cuộc vận động bị trừ 02 điểm, từ lần vi phạm thứ hai trở đi bị trừ hết số điểm còn lại của tiêu chí',1,'1/1/2018')
insert into TieuChi values (2,N'Có ý thức chấp hành nội quy, quy chế, thực hiện nội quy văn hóa học đường và các quy định của nhà trường',0,N'Vi phạm 01 lần bị trừ 02 điểm, từ lần vi phạm thứ ba trở đi bị trừ hết số điểm còn lại của tiêu chí',1,'1/1/2018')
insert into TieuChi values (2,N'Tham gia đầy đủ, đạt yêu cầu “Tuần sinh hoạt công dân sinh viên”',2,N'đánh giá chung cho cả hai học kỳ trong năm học',1,'1/1/2018')
insert into TieuChi values (3,N'Tham gia các hoạt động, sinh hoạt phong trào, tình nguyện do Khoa tổ chức',0,N'Vắng 01 lần (không có phép) bị trừ 02 điểm',1,'1/1/2018')
insert into TieuChi values (3,N'Tham gia các hoạt động do Đoàn thanh niên và Hội sinh viên tổ chức',0,N'tham gia 1 hoạt động được 2 điểm',1,'1/1/2018')
insert into TieuChi values (3,N'Có ý thức tham gia đầy đủ, nghiêm túc hoạt động rèn luyện về chính trị, xã hội, văn hóa, văn nghệ, thể thao do nhà trường tổ chức, điều động',2,null,1,'1/1/2018')
insert into TieuChi values (3,N'Có ý thức tham gia các hoạt động công ích, tình nguyện, công tác xã hội trong nhà trường',2,null,1,'1/1/2018')
insert into TieuChi values (3,N'Có ý thức tham gia các hoạt động tuyên truyền, phòng chống tội phạm và các tệ nạn xã hội trong nhà trường',2,null,1,'1/1/2018')
insert into TieuChi values (4,N'Có ý thức chấp hành, tham gia tuyên truyền các chủ trương của Đảng, chính sách, pháp luật của Nhà nước',0,N'Vi phạm 01 lần bị trừ 02 điểm, từ lần vi phạm thứ hai trở đi bị trừ hết số điểm còn lại của tiêu chí',1,'1/1/2018')
insert into TieuChi values (4,N'Có tham gia bảo hiểm y tế (bắt buộc) theo Luật bảo hiểm y tế',0,N'thực hiện đầy đủ: 10 điểm; không thực hiện: 0 điểm',1,'1/1/2018')
insert into TieuChi values (4,N'Có ý thức chấp hành, tham gia tuyên truyền các quy định về bảo đảm an toàn giao thông và “văn hóa giao thông”',0,N'Vi phạm 01 lần bị trừ 02 điểm, từ lần vi phạm thứ hai trở đi bị trừ hết số điểm còn lại của tiêu chí',1,'1/1/2018')
insert into TieuChi values (4,N'Có ý thức tham gia các hoạt động xã hội có thành tích được ghi nhận, biểu dương, khen thưởng',2,null,1,'1/1/2018')
insert into TieuChi values (4,N'Có tinh thần chia sẻ, giúp đỡ người gặp khó khăn, hoạn nạn',2,null,1,'1/1/2018')
insert into TieuChi values (5,N'Có ý thức, uy tín và hoàn thành tốt nhiệm vụ quản lý lớp, các tổ chức Đảng, Đoàn Thanh niên, Hội Sinh viên, tổ chức khác trong nhà trường',2,null,1,'1/1/2018')
insert into TieuChi values (5,N'Có kỹ năng tổ chức, quản lý lớp, các tổ chức Đảng, Đoàn Thanh niên, Hội Sinh viên và các tổ chức khác trong nhà trường',2,null,1,'1/1/2018')
insert into TieuChi values (5,N'Hỗ trợ và tham gia tích cực các hoạt động chung của tập thể lớp, khoa, trường, tham gia ban tự quản khu nội trú',2,null,1,'1/1/2018')
insert into TieuChi values (5,N'Đạt thành tích trong học tập, rèn luyện',2,N'được tặng bằng khen, giấy khen, chứng nhận, thư khen của các cấp',1,'1/1/2018')

insert into TuyChonTieuChi values (4,N'Không bị kỷ luật')
insert into TuyChonTieuChi values (4,N'Khiển trách')
insert into TuyChonTieuChi values (4,N'Cảnh cáo')
insert into TuyChonTieuChi values (4,N'Đình chỉ thi')
insert into TuyChonTieuChi values (6,N'Yếu kém')
insert into TuyChonTieuChi values (6,N'Trung bình')
insert into TuyChonTieuChi values (6,N'Khá')
insert into TuyChonTieuChi values (6,N'Giỏi')
insert into TuyChonTieuChi values (6,N'Xuất sắc')
insert into TuyChonTieuChi values (7,N'Không vi phạm')
insert into TuyChonTieuChi values (7,N'Vi phạm 1 lần')
insert into TuyChonTieuChi values (7,N'Vi phạm 2 lần trở lên')
insert into TuyChonTieuChi values (8,N'Tham gia đầy đủ')
insert into TuyChonTieuChi values (8,N'Không tham gia 1 lần')
insert into TuyChonTieuChi values (8,N'Vi phạm quy định')
insert into TuyChonTieuChi values (8,N'Vi phạm lần 2 trở lên')
insert into TuyChonTieuChi values (9,N'Không vi phạm')
insert into TuyChonTieuChi values (9,N'Vi phạm 1 lần')
insert into TuyChonTieuChi values (9,N'Vi phạm 2 lần')
insert into TuyChonTieuChi values (9,N'Vi phạm 3 lần trở lên')
insert into TuyChonTieuChi values (11,N'Tham gia đầy đủ')
insert into TuyChonTieuChi values (11,N'Văng 1 lần')
insert into TuyChonTieuChi values (11,N'Vắng 2 lần')
insert into TuyChonTieuChi values (11,N'Vắng 3 lần trở lên')
insert into TuyChonTieuChi values (12,N'Không tham gia')
insert into TuyChonTieuChi values (12,N'Tham gia 1 lần')
insert into TuyChonTieuChi values (12,N'Tham gia 2 lần')
insert into TuyChonTieuChi values (12,N'Tham gia 3 lần trở lên')
insert into TuyChonTieuChi values (16,N'Không vi phạm')
insert into TuyChonTieuChi values (16,N'Vi phạm 1 lần')
insert into TuyChonTieuChi values (16,N'Vi phạm 2 lần trở lên')
insert into TuyChonTieuChi values (17,N'Thực hiện đầy đủ')
insert into TuyChonTieuChi values (17,N'Không thực hiện')
insert into TuyChonTieuChi values (18,N'Không vi phạm')
insert into TuyChonTieuChi values (18,N'Vi phạm 1 lần')
insert into TuyChonTieuChi values (18,N'Vi phạm 2 lần trở lên')

insert into BoTieuChi values (1,'2019-2020',1,'1/1/2020',1)
insert into BoTieuChi values (1,'2018-2019',1,'1/1/2020',1)

insert into ChiTietBoTieuChi values (1,1,4,0)
insert into ChiTietBoTieuChi values (1,2,2,0)
insert into ChiTietBoTieuChi values (1,3,2,0)
insert into ChiTietBoTieuChi values (1,4,0,null)
insert into ChiTietBoTieuChi values (1,5,2,0)
insert into ChiTietBoTieuChi values (1,6,10,null)
insert into ChiTietBoTieuChi values (1,7,6,null)
insert into ChiTietBoTieuChi values (1,8,4,null)
insert into ChiTietBoTieuChi values (1,9,10,null)
insert into ChiTietBoTieuChi values (1,10,5,0)
insert into ChiTietBoTieuChi values (1,11,6,null)
insert into ChiTietBoTieuChi values (1,12,6,null)
insert into ChiTietBoTieuChi values (1,13,4,0)
insert into ChiTietBoTieuChi values (1,14,2,0)
insert into ChiTietBoTieuChi values (1,15,2,0)
insert into ChiTietBoTieuChi values (1,16,4,null)
insert into ChiTietBoTieuChi values (1,17,10,null)
insert into ChiTietBoTieuChi values (1,18,5,null)
insert into ChiTietBoTieuChi values (1,19,4,0)
insert into ChiTietBoTieuChi values (1,20,2,0)
insert into ChiTietBoTieuChi values (1,21,3,0)
insert into ChiTietBoTieuChi values (1,22,2,0)
insert into ChiTietBoTieuChi values (1,23,3,0)
insert into ChiTietBoTieuChi values (1,24,2,0)
insert into ChiTietBoTieuChi values (2,1,4,0)
insert into ChiTietBoTieuChi values (2,2,2,0)
insert into ChiTietBoTieuChi values (2,3,2,0)
insert into ChiTietBoTieuChi values (2,4,0,null)
insert into ChiTietBoTieuChi values (2,5,2,0)
insert into ChiTietBoTieuChi values (2,6,10,null)
insert into ChiTietBoTieuChi values (2,7,6,null)
insert into ChiTietBoTieuChi values (2,8,4,null)
insert into ChiTietBoTieuChi values (2,9,10,null)
insert into ChiTietBoTieuChi values (2,10,5,0)
insert into ChiTietBoTieuChi values (2,11,6,null)
insert into ChiTietBoTieuChi values (2,12,6,null)
insert into ChiTietBoTieuChi values (2,13,4,0)
insert into ChiTietBoTieuChi values (2,14,2,0)
insert into ChiTietBoTieuChi values (2,15,2,0)
insert into ChiTietBoTieuChi values (2,16,4,null)
insert into ChiTietBoTieuChi values (2,17,10,null)
insert into ChiTietBoTieuChi values (2,18,5,null)
insert into ChiTietBoTieuChi values (2,19,4,0)
insert into ChiTietBoTieuChi values (2,20,2,0)
insert into ChiTietBoTieuChi values (2,21,3,0)
insert into ChiTietBoTieuChi values (2,22,2,0)
insert into ChiTietBoTieuChi values (2,23,3,0)
insert into ChiTietBoTieuChi values (2,24,2,0)

insert into DiemTuyChon values (4,1,0)
insert into DiemTuyChon values (4,2,-2)
insert into DiemTuyChon values (4,3,-4)
insert into DiemTuyChon values (4,4,-6)
insert into DiemTuyChon values (6,5,0)
insert into DiemTuyChon values (6,6,4)
insert into DiemTuyChon values (6,7,6)
insert into DiemTuyChon values (6,8,8)
insert into DiemTuyChon values (6,9,10)
insert into DiemTuyChon values (7,10,6)
insert into DiemTuyChon values (7,11,4)
insert into DiemTuyChon values (7,12,0)
insert into DiemTuyChon values (8,13,4)
insert into DiemTuyChon values (8,14,2)
insert into DiemTuyChon values (8,15,2)
insert into DiemTuyChon values (8,16,0)
insert into DiemTuyChon values (9,17,10)
insert into DiemTuyChon values (9,18,8)
insert into DiemTuyChon values (9,19,6)
insert into DiemTuyChon values (9,20,0)
insert into DiemTuyChon values (11,21,6)
insert into DiemTuyChon values (11,22,4)
insert into DiemTuyChon values (11,23,2)
insert into DiemTuyChon values (11,24,0)
insert into DiemTuyChon values (12,25,0)
insert into DiemTuyChon values (12,26,2)
insert into DiemTuyChon values (12,27,4)
insert into DiemTuyChon values (12,28,6)
insert into DiemTuyChon values (16,29,4)
insert into DiemTuyChon values (16,30,2)
insert into DiemTuyChon values (16,31,0)
insert into DiemTuyChon values (17,32,10)
insert into DiemTuyChon values (17,33,0)
insert into DiemTuyChon values (18,34,5)
insert into DiemTuyChon values (18,35,3)
insert into DiemTuyChon values (18,36,0)
insert into DiemTuyChon values (28,1,0)
insert into DiemTuyChon values (28,2,-2)
insert into DiemTuyChon values (28,3,-4)
insert into DiemTuyChon values (28,4,-6)
insert into DiemTuyChon values (30,5,0)
insert into DiemTuyChon values (30,6,4)
insert into DiemTuyChon values (30,7,6)
insert into DiemTuyChon values (30,8,8)
insert into DiemTuyChon values (30,9,10)
insert into DiemTuyChon values (31,10,6)
insert into DiemTuyChon values (31,11,4)
insert into DiemTuyChon values (31,12,0)
insert into DiemTuyChon values (32,13,4)
insert into DiemTuyChon values (32,14,2)
insert into DiemTuyChon values (32,15,2)
insert into DiemTuyChon values (32,16,0)
insert into DiemTuyChon values (33,17,10)
insert into DiemTuyChon values (33,18,8)
insert into DiemTuyChon values (33,19,6)
insert into DiemTuyChon values (33,20,0)
insert into DiemTuyChon values (35,21,6)
insert into DiemTuyChon values (35,22,4)
insert into DiemTuyChon values (35,23,2)
insert into DiemTuyChon values (35,24,0)
insert into DiemTuyChon values (36,25,0)
insert into DiemTuyChon values (36,26,2)
insert into DiemTuyChon values (36,27,4)
insert into DiemTuyChon values (36,28,6)
insert into DiemTuyChon values (40,29,4)
insert into DiemTuyChon values (40,30,2)
insert into DiemTuyChon values (40,31,0)
insert into DiemTuyChon values (41,32,10)
insert into DiemTuyChon values (41,33,0)
insert into DiemTuyChon values (42,34,5)
insert into DiemTuyChon values (42,35,3)
insert into DiemTuyChon values (42,36,0)


select * from TaiKhoan
select * from NhomTieuChi
select * from TieuChi
select * from TuyChonTieuChi
select * from BoTieuChi
select * from ChiTietBoTieuChi
select * from DiemTuyChon